### ISSUE TITLE
get_clean_html: lxml error 

### ISSUE THREAD

**Issue by dufferzafar** [buriy/python-readability#108]
```python
>>> u = "https://www.geeksforgeeks.org/samsung-research-institute-bangalore-srib-intern/"

>>> import requests

>>> r = requests.get(u)

>>> from readability import Document

>>> doc = Document(r.content)

>>> doc.get_clean_html()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dufferzafar/.local/lib/python3.7/site-packages/readability/readability.py", line 167, in get_clean_html
    return clean_attributes(tounicode(self.html))
  File "src/lxml/etree.pyx", line 3397, in lxml.etree.tounicode
TypeError: Type '<class 'NoneType'>' cannot be serialized.
Type '<class 'NoneType'>' cannot be serialized.
```

**Comment by dufferzafar** [comment]
The `doc.summary()` method works, but it doesn't seem to have all the data that we want.

**Comment by dufferzafar** [comment]
And I think I've found the error. 

[Line 9 of the file](https://github.com/buriy/python-readability/blob/master/readability/readability.py#L170) should actually be:

```python
   return clean_attributes(tounicode(self._html(True)))
```

So that it forces the `self.html` attribute to be set.

Gonna roll with this change for now.

**Comment by buriy** [comment]
get_clean_html is made for summary cleaning up, not for the full doc cleaning up.
You can clean the full doc yourself, you don't need this lib for that ;)

**Comment by MChrys** [comment]
I get the same error even if i used get_clean_html only on requests.get(url).text, but only on a spécifique url :https://start.lesechos.fr/travailler-a-letranger/actu-internationales/expatriation-les-pays-qui-chouchoutent-le-plus-les-talents-13988.php

I can't use summary() in my case because, i'm using readability on french pages and summary() read special character like 'é' as ascii unicode, and the section which contain this kind of character don't get a score good enough to appear in the summary() text .

**Comment by buriy** [comment]
Fixed in [0.9](https://github.com/buriy/python-readability/releases/tag/0.9). `get_clean_html()` now initializes the parsed document correctly when called before another document API.
