### ISSUE TITLE
Issue with Medium pages

### ISSUE THREAD

**Issue by Andre0991** [buriy/python-readability#71]
Hi.

I'm getting some errors when trying to process any page from Medium:

```
$ python -m readability.readability -u https://medium.com/thoughts-on-media/i-read-because-we-re-all-storytellers-it-s-human-nature-after-all-d957a9d2e621#.rn719ccdw
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/readability/readability.py", line 624, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/readability/readability.py", line 600, in main
    file = urllib2.urlopen(options.url)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

At first I thought it could have something to do with special characters present on the url, but the same thing happens with Medium's homepage:

```
$ python -m readability.readability -u https://medium.com/
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/readability/readability.py", line 624, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/readability/readability.py", line 600, in main
    file = urllib2.urlopen(options.url)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

Thanks.

**Comment by buriy** [comment]
Hi,

"Forbidden" means they don't let us download the page.

One needs to change user agent, most probably:
http://stackoverflow.com/a/5196160/217895
But that's an interesting question, maybe we should send fake user agent
for scraping purposes by default.

On Wed, Dec 9, 2015 at 8:58 PM, Andre0991 <notifications@github.com> wrote:

> Hi.
>
> I'm getting some errors when trying to process any page from Medium:
>
> $ python -m readability.readability -u https://medium.com/thoughts-on-media/i-read-because-we-re-all-storytellers-it-s-human-nature-after-all-d957a9d2e621#.rn719ccdw
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/usr/local/lib/python2.7/site-packages/readability/readability.py", line 624, in <module>
>     main()
>   File "/usr/local/lib/python2.7/site-packages/readability/readability.py", line 600, in main
>     file = urllib2.urlopen(options.url)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
>     response = meth(req, response)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
>     return self._call_chain(*args)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
>     result = func(*args)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> urllib2.HTTPError: HTTP Error 403: Forbidden
>
> At first I thought it could have something to do with special characters
> present on the url, but the same thing happens with Medium's homepage:
>
> $ python -m readability.readability -u https://medium.com/
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/usr/local/lib/python2.7/site-packages/readability/readability.py", line 624, in <module>
>     main()
>   File "/usr/local/lib/python2.7/site-packages/readability/readability.py", line 600, in main
>     file = urllib2.urlopen(options.url)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
>     response = meth(req, response)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
>     return self._call_chain(*args)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
>     result = func(*args)
>   File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> urllib2.HTTPError: HTTP Error 403: Forbidden
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buriy/python-readability/issues/71>.
>



-- 
Best regards, Yuri V. Baburov, Skype: yuri.baburov

**Comment by Andre0991** [comment]
Ah, OK.

I agree with your suggestion :)

**Comment by WangErGou** [comment]
Maybe we should do this in `readability.main()` ?

**Comment by alphapapa** [comment]
Seeing this myself.  Using this fixes it:

```
headers = { 'User-Agent' : 'Mozilla/5.0' }
req = urllib2.Request(options.url, None, headers)
file = urllib2.urlopen(req)
```

**Comment by Andre0991** [comment]
Thanks @alphapapa :+1:
